--5.MAGNITUTDE ANALYSIS(COMPARING MEASURE VALUES BY CATEGORIES)
--THIS WILL HELP IN UNDERSTANDING THE IMPORTANCE OF DIFFERENT CATEGORIES
--FORMULA-- MEASURE BY DIMENSION

--finding total customers by countries
SELECT country , count(customer_key) as total_customers FROM gold.dim_customers
group by country
order by total_customers desc

--customers by gender
SELECT gender, count(customer_key) as total_customers FROM gold.dim_customers
group by gender
order by total_customers desc

--products by category
SELECT category, count(product_key) as total_products FROM gold.dim_products
group by category
order by total_products desc

--avg cost in each category
SELECT category, avg(cost) as avg_cost FROM gold.dim_products
group by category
order by avg_cost desc

--total revenue generated for each category
SELECT p.category , SUM(f.sales_amount) as total_revenue FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.product_key=p.product_key
group by p.category
order by total_revenue desc

--total revenue generated by each customer
SELECT c.customer_key ,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue FROM gold.fact_sales f
LEFT JOIN
gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,c.first_name, c.last_name
order by total_revenue desc

--distribution of sold items accross countries
SELECT c.country , SUM(quantity) as total_quantity FROM gold.fact_sales f
LEFT JOIN
gold.dim_customers c
on f.customer_key=c.customer_key
group by c.country
order by total_quantity desc;
------------------------------------------------------------