--- MEASURE VS DIMENSION
-- IF DATA TYPE IS NUMBER AND IT CAN BE CALCULATED THEN ITS A MEASURE OR ELSE ITS A DIMENSION

--EXPLORATORY DATA ANALYSIS

--1.DATABASE EXPLORATION
USE DataWarehouseAnalytics;

--exploring all the objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--exploring all the columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
--------------------------------------------------------

-- 2.DIMENSION EXPLORATION

--exploring all the countries where from customers come from
select distinct country from gold.dim_customers;

--exploring all the categories-"THE MAJOR DIVISIONS"
select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3;
-------------------------------------------------------

--3.DATE EXPLORATION

--checking the earliest and the latest date(boundaries)
--date of first and last order
select MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date,
DATEDIFF(YEAR, min(order_date), max(order_date)) as order_range_years,
DATEDIFF(MONTH, min(order_date), max(order_date)) as order_range_months
from gold.fact_sales

--finding the youngest and the oldest customer
select MAX(birthdate) as youngest_customer, 
MIN(birthdate) as oldest_customer,
DATEDIFF(YEAR, max(birthdate), GETDATE()) as age_of_youngest,
DATEDIFF(YEAR, min(birthdate), GETDATE()) as age_of_oldest
from gold.dim_customers
------------------------------------------------------------

--4.MEASURES EXPLORATION(BIG NUMBERS)

--finding total sales
SELECT sum(sales_amount) as total_sales FROM gold.fact_sales

--how many items are sold
SELECT sum(quantity) as total_qauntity FROM gold.fact_sales

--avg selling price
SELECT avg(price) as avg_price FROM gold.fact_sales

--total number of orders
SELECT count(distinct order_number) FROM gold.fact_sales

--total number of products
SELECT count(distinct product_name) FROM gold.dim_products

--total number of customers
SELECT count(customer_key) FROM gold.dim_customers
--or
SELECT count(distinct customer_key) FROM gold.fact_sales

---NOW GENERATING A REPORT THAT SHOWS ALL THE KEY METRICS OF OUR BUSINESS
SELECT 'TOTAL SALES' AS measure_name,  sum(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL QUANTITY' , sum(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'AVG PRICE', avg(price) FROM gold.fact_sales
UNION ALL
SELECT 'NUMBER OF ORDERS', COUNT(distinct order_number) FROM gold.fact_sales
UNION ALL
SELECT 'TOTAL NO OF PRODUCTS', COUNT(distinct product_name) FROM gold.dim_products
UNION ALL
SELECT 'TOTAL CUSTOMERS' , COUNT(distinct customer_key) FROM gold.dim_customers;
------------------------------------------------------------

--5.MAGNITUTDE ANALYSIS(COMPARING MEASURE VALUES BY CATEGORIES)
--THIS WILL HELP IN UNDERSTANDING THE IMPORTANCE OF DIFFERENT CATEGORIES
--FORMULA-- MEASURE BY DIMENSION

--finding total customers by countries
SELECT country , count(customer_key) as total_customers FROM gold.dim_customers
group by country
order by total_customers desc

--customers by gender
SELECT gender, count(customer_key) as total_customers FROM gold.dim_customers
group by gender
order by total_customers desc

--products by category
SELECT category, count(product_key) as total_products FROM gold.dim_products
group by category
order by total_products desc

--avg cost in each category
SELECT category, avg(cost) as avg_cost FROM gold.dim_products
group by category
order by avg_cost desc

--total revenue generated for each category
SELECT p.category , SUM(f.sales_amount) as total_revenue FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.product_key=p.product_key
group by p.category
order by total_revenue desc

--total revenue generated by each customer
SELECT c.customer_key ,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue FROM gold.fact_sales f
LEFT JOIN
gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,c.first_name, c.last_name
order by total_revenue desc

--distribution of sold items accross countries
SELECT c.country , SUM(quantity) as total_quantity FROM gold.fact_sales f
LEFT JOIN
gold.dim_customers c
on f.customer_key=c.customer_key
group by c.country
order by total_quantity desc;
------------------------------------------------------------

--6.RANKING ANALYSIS
--ordering the values of dimensions by measures
--FORMULA:- ranking(dimension) by measure

--top 5 products generating the highest revenue
SELECT TOP 5
p.product_name, sum(f.sales_amount) as total_revenue FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by total_revenue desc

--using window function row_number
SELECT * FROM(
SELECT
p.product_name, sum(f.sales_amount) as total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) desc) as rank_products
FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.product_key = p.product_key
group by p.product_name)t
where rank_products <=5


--*****************************************************************


--worst 5 performing products in terms of sales
SELECT TOP 5
p.product_name, sum(f.sales_amount) as total_revenue FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by total_revenue asc


--using window function row_number
SELECT * FROM(
SELECT
p.product_name, sum(f.sales_amount) as total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) asc) as rank_products
FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.product_key = p.product_key
group by p.product_name)t
where rank_products <=5

----******************************************************************************************************
----******************************************************************************************************

-- ADVANCE DATA ANALYSIS

--7. CHANGE OVER TIME ANALYSIS(IT GIVES A HIGH-LEVEL OVERVIEW INSIGHTS THAT HELPS WITH STRATEGIC DECISION MAKING)
--ANALYSING HOW MEASURE EVOLVES OVER TIME
--IT HELPS TO TRACK TRENDS AND IDENTIFY SEASONALITY OVER DATA
--FORMULA:- MEASURE BY DATE DIMENSION

--analyse the sales performance, customers, quantity over time(years)
SELECT YEAR(order_date) as order_year ,
SUM(sales_amount) as total_sales,
COUNT(distinct customer_key) as total_customers,
COUNT(distinct product_key) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date)

--analyse the sales performance, customers, quantity over time(months)
SELECT MONTH(order_date) as order_year ,
SUM(sales_amount) as total_sales,
COUNT(distinct customer_key) as total_customers,
COUNT(distinct product_key) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY MONTH(order_date)
ORDER BY MONTH(order_date)

--OR-----

SELECT DATENAME(month,order_date) as order_year ,
SUM(sales_amount) as total_sales,
COUNT(distinct customer_key) as total_customers,
COUNT(distinct product_key) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATENAME(month,order_date)
ORDER BY DATENAME(month,order_date)

--OR BOTH(months and year) in one

SELECT DATETRUNC(month ,order_date) as order_year ,
SUM(sales_amount) as total_sales,
COUNT(distinct customer_key) as total_customers,
COUNT(distinct product_key) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month ,order_date)
ORDER BY DATETRUNC(month ,order_date);
--*************************************************************************


--8.CUMULATIVE ANALYSIS(AGGREGATING THE DATA PROGRESSIVELY OVER TIME)
--IT HELPS TO UNDERSTAND WHETHER OUR BUSINESS IS GROWING OR DECLINING
--FORMULA :- CUMULATIVE MEASURE BY DATE DIMENSION

--calculating the total sales per month and running total sales over time
SELECT 
order_date,
total_sales,
SUM(total_sales) over(partition  by order_date order by order_date) as running_total_sales
FROM(
SELECT DATETRUNC(month ,order_date) as order_date,
SUM(sales_amount) as total_sales
FROM gold.fact_sales	
where order_date is not null
GROUP BY DATETRUNC(month ,order_date)
)t

--or---
--(SPECIFIALLY BY YEAR)...ALSO CHECKING THE MOVING AVG
SELECT 
order_date,
total_sales,
avg_price,
SUM(total_sales) over(order by order_date) as running_total_sales,
AVG(avg_price) over(order by order_date) as moving_avg_price
FROM(
SELECT DATETRUNC(year ,order_date) as order_date,
SUM(sales_amount) as total_sales,
AVG(price) as avg_price
FROM gold.fact_sales	
where order_date is not null
GROUP BY DATETRUNC(year ,order_date)
)t;
--****************************************************************************


--9.PERFROMANCE ANALYSIS(COMPARING CURRENT VALUE WITH TARGET VALUE)
--IT HELPS MEASURE SUCCESS AND COMPARE PERFORMANCE
--FORMULA:- CURRENT MEASURE - TARGET MEASURE

--analysing the yearly performance of products by comparing each product's sales to both its avg sales performance and the previous year's sales(USING CTE)
WITH yearly_product_sales as(
SELECT 
YEAR(f.order_date) as order_year,
p.product_name,
SUM(f.sales_amount) as current_sales
FROM gold.fact_sales f
LEFT  JOIN
gold.dim_products p
on f.product_key = p.product_key
WHERE f.order_date is not null
GROUP BY YEAR(f.order_date), p.product_name)

--(COMPARING THE CURRENT SALES WITH THE AVG SALES)
SELECT
product_name,
order_year,
current_sales,
AVG(current_sales) OVER(PARTITION BY product_name) as avg_sales,
current_sales - AVG(current_sales) OVER(PARTITION BY product_name) as difference_in_avg,
CASE WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) > 0 THEN 'ABOVE AVERAGE'
	 WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) < 0 THEN 'BELOW AVERAGE'
	 ELSE 'AVERAGE'
END as avg_change
FROM yearly_product_sales
ORDER BY product_name, order_year;
----&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

--(COMPARING THE CURRENT SALES WITH THE PREVIOUS YEAR'S SALES)
WITH yearly_product_sales as(
SELECT 
YEAR(f.order_date) as order_year,
p.product_name,
SUM(f.sales_amount) as current_sales
FROM gold.fact_sales f
LEFT  JOIN
gold.dim_products p
on f.product_key = p.product_key
WHERE f.order_date is not null
GROUP BY YEAR(f.order_date), p.product_name)

SELECT
product_name,
order_year,
current_sales,
LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) as previous_year_sales,
current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) as diff_in_previous_sales,
CASE WHEN current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) > 0 THEN 'INCREASING'
	 WHEN current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) < 0 THEN 'DECREASING'
	 ELSE 'NO CHANGE'
END as previous_year_change
FROM yearly_product_sales
WHERE order_year is not null
ORDER BY product_name, order_year;
--****************************************************************************


--10.PART TO WHOLE ANALYSIS(PROPORTIONAL)
--IT HELPS TO ANALYSE HOW AN INDIVIDUAL PART IS PERFORMING COMPARED TO THE OVERALL, ALLOWING US TO UNDERSTAND WHICH CATEGORY HAS THE GREATEST IMPACT ON BUSINESS
--FORMULA:- (MEASURE / TOTAL MEASURE) * 100    BY CATEGORY

--category that contributes the most to overall sales(USING CTE)
WITH category_sales AS(
SELECT 
p.category,
SUM(f.sales_amount) as total_sales
FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
ON f.product_key = p.product_key
GROUP BY category)

SELECT 
category,
total_sales,
SUM(total_sales) OVER() as overall_sales,
CONCAT(ROUND((CAST (total_sales as FLOAT)/ SUM(total_sales) OVER() )* 100, 2), '%') as percentage_of_total
FROM category_sales
ORDER BY total_sales desc;
--****************************************************************************************


--11.DATA SEGMENTATION (GROUPING THE DATA BASED ON SPECIFIC RANGE)
--IT HELPS TO UNDERSTAND THE CORRELATION BETWEEN TWO MEASURES
--FORMULA:- MEASURE BY MEASURE

--segmenting products into cost ranges and counting how many products fall into each segment(USING CTE)
WITH product_segments AS (
SELECT 
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'BELOW 100'
	 WHEN cost between 100 and 500 THEN '100-500'
	 WHEN cost between 500 and 1000 THEN '500-1000'
	 ELSE 'ABOVE 1000'
END as cost_range
FROM gold.dim_products)

SELECT 
cost_range,
count(product_key) as total_products
FROM product_segments
GROUP BY cost_range
ORDER BY total_products DESC;
--&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

--grouping customers into three segments based on their spending behavior
--VIP:- at least 12 months
--REGULAR:- at least 12 months of history but spending 5000 or less
--NEW:- lifespan less than 12 months
--and finding the total number of customers by each group
--(USING CTE)
WITH customer_spending AS(
SELECT
c.customer_key,
SUM(f.sales_amount) as total_spending,
MIN(order_date) as first_order,
MAX(order_date) as last_order,
DATEDIFF(month, min(order_date) , max(order_date) ) as lifespan
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
on f.customer_key = c.customer_key
GROUP BY c.customer_key
)

--(selecting from my cte but also a subquery for better readability)
SELECT customer_segment ,  
count(customer_key) as total_customers
FROM(
SELECT
customer_key,
CASE WHEN lifespan >= 12 AND total_spending > 5000 THEN 'VIP'
     WHEN lifespan >= 12 AND total_spending <= 5000 THEN 'REGULAR' 
	 ELSE 'NEW'
END as customer_segment
FROM customer_spending)t
GROUP BY customer_segment
ORDER BY total_customers desc;
--****************************************************************************************
--****************************************************************************************
